### ISSUE TITLE
Question: How do you logout?

### ISSUE THREAD

**Issue by madhan5000** [ongoworks/meteor-ddp-login#3]
Authors, Thanks for the great package. Just curious to know how to logout? Thanks !

**Comment by aaronjudd** [comment]
Give this a shot:

http://docs.meteor.com/#/full/meteor_logout

```
conn.logout();
```

**Comment by madhan5000** [comment]
Great !! Thanks !

**Comment by aldeed** [comment]
Or :arrow_up: :arrow_up: :arrow_down: :arrow_down: :arrow_left: :arrow_right: :arrow_left: :arrow_right: B A

:wink:

**Comment by jshimko** [comment]
Nicely done @aldeed, nicely done.
